name: Run On Windows

on:
  workflow_dispatch:

jobs:
  run:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
#          python-version-file: '.python-version'
          python-version: '3.8.7'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'

      - name: Install Requirements Windows
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Set time zone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: Run
        env:
          DJC_HELPER_CONFIG_TOML: ${{ secrets.DJC_HELPER_CONFIG_TOML }}
        run: |
          echo "$DJC_HELPER_CONFIG_TOML" > ./config.toml
          python main.py
