name: Run On Docker

on:
  workflow_dispatch:

jobs:
  run:

    runs-on: ubuntu-latest
    container:
      image: fzls/djc_helper:master
      env:
        DJC_HELPER_CONFIG_TOML: ${{ secrets.DJC_HELPER_CONFIG_TOML }}
    steps:
      - name: Run
        run: |
          cd /djc_helper
          python3 main.py
