name: Run On Ubuntu

on:
  workflow_dispatch:

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'

      - name: Install Requirements Ubuntu
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements_linux.txt

      - name: Set time zone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: Chrome And Driver Cache On Ubuntu
        id: chrome-cache
        uses: actions/cache@v4
        with:
          path: |
            google-chrome*.deb
            chromedriver
          key: ${{ runner.os }}-chrome-${{ hashFiles('_ubuntu_download_chrome_and_driver.sh') }}
          restore-keys: |
            ${{ runner.os }}-chrome-

      - name: Download Chrome And Driver Ubuntu
        if: steps.chrome-cache.outputs.cache-hit != 'true'
        run: |
          bash _ubuntu_download_chrome_and_driver.sh

      - name: Install Chrome And Driver Ubuntu
        run: |
          bash _ubuntu_install_chrome_and_driver.sh

      - name: Run
        env:
          DJC_HELPER_CONFIG_TOML: ${{ secrets.DJC_HELPER_CONFIG_TOML }}
        run: |
          echo "$DJC_HELPER_CONFIG_TOML" > ./config.toml
          python main.py
